//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 11:30:49 AM MSK 
//


package by.it.uskoryaev.jd02_09;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Car complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Car">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BodyCar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="YearRelease" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CreateReport" type="{http://jd02_09.uskoryaev.it.by}CreateReport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = {
        "carID",
        "serialNumber",
        "brand",
        "model",
        "bodyCar",
        "yearRelease",
        "color",
        "userID",
        "createReport"
})
public class Car {

    @XmlElement(name = "CarID", required = true)
    protected BigInteger carID;
    @XmlElement(name = "SerialNumber", required = true)
    protected String serialNumber;
    @XmlElement(name = "Brand", required = true)
    protected String brand;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "BodyCar", required = true)
    protected String bodyCar;
    @XmlElement(name = "YearRelease", required = true)
    protected String yearRelease;
    @XmlElement(name = "Color", required = true)
    protected String color;
    @XmlElement(name = "UserID", required = true)
    protected BigInteger userID;
    @XmlElement(name = "CreateReport", required = true)
    protected CreateReport createReport;

    /**
     * Gets the value of the carID property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getCarID() {
        return carID;
    }

    /**
     * Sets the value of the carID property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setCarID(BigInteger value) {
        this.carID = value;
    }

    /**
     * Gets the value of the serialNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the brand property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the bodyCar property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBodyCar() {
        return bodyCar;
    }

    /**
     * Sets the value of the bodyCar property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBodyCar(String value) {
        this.bodyCar = value;
    }

    /**
     * Gets the value of the yearRelease property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getYearRelease() {
        return yearRelease;
    }

    /**
     * Sets the value of the yearRelease property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setYearRelease(String value) {
        this.yearRelease = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the userID property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setUserID(BigInteger value) {
        this.userID = value;
    }

    /**
     * Gets the value of the createReport property.
     *
     * @return possible object is
     * {@link CreateReport }
     */
    public CreateReport getCreateReport() {
        return createReport;
    }

    /**
     * Sets the value of the createReport property.
     *
     * @param value allowed object is
     *              {@link CreateReport }
     */
    public void setCreateReport(CreateReport value) {
        this.createReport = value;
    }

    @Override
    public String toString() {
        return "Car{" +
                "carID=" + carID +
                ", serialNumber='" + serialNumber + '\'' +
                ", brand='" + brand + '\'' +
                ", model='" + model + '\'' +
                ", bodyCar='" + bodyCar + '\'' +
                ", yearRelease='" + yearRelease + '\'' +
                ", color='" + color + '\'' +
                ", userID=" + userID +
                ", createReport=" + createReport +
                '}';
    }
}
