//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 11:30:49 AM MSK 
//


package by.it.uskoryaev.jd02_09;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Report complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Report">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BrandAndModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Commission" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TotalCost" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CarID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Report", propOrder = {
    "reportID",
    "brandAndModel",
    "dataOrder",
    "commission",
    "cost",
    "totalCost",
    "carID"
})
public class Report {
    @Override
    public String toString() {
        return "Report{" +
                "reportID=" + reportID +
                ", brandAndModel='" + brandAndModel + '\'' +
                ", dataOrder='" + dataOrder + '\'' +
                ", commission=" + commission +
                ", cost=" + cost +
                ", totalCost=" + totalCost +
                ", carID=" + carID +
                '}';
    }

    @XmlElement(name = "ReportID", required = true)
    private BigInteger reportID;
    @XmlElement(name = "BrandAndModel", required = true)
    private String brandAndModel;
    @XmlElement(name = "DataOrder", required = true)
    protected String dataOrder;
    @XmlElement(name = "Commission", required = true)
    protected BigInteger commission;
    @XmlElement(name = "Cost", required = true)
    protected BigInteger cost;
    @XmlElement(name = "TotalCost", required = true)
    protected BigInteger totalCost;
    @XmlElement(name = "CarID", required = true)
    protected BigInteger carID;

    /**
     * Gets the value of the reportID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReportID() {
        return reportID;
    }

    /**
     * Sets the value of the reportID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReportID(BigInteger value) {
        this.reportID = value;
    }

    /**
     * Gets the value of the brandAndModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandAndModel() {
        return brandAndModel;
    }

    /**
     * Sets the value of the brandAndModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandAndModel(String value) {
        this.brandAndModel = value;
    }

    /**
     * Gets the value of the dataOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOrder() {
        return dataOrder;
    }

    /**
     * Sets the value of the dataOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOrder(String value) {
        this.dataOrder = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommission() {
        return commission;
    }

    /**
     * Sets the value of the commission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommission(BigInteger value) {
        this.commission = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCost(BigInteger value) {
        this.cost = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalCost(BigInteger value) {
        this.totalCost = value;
    }

    /**
     * Gets the value of the carID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCarID() {
        return carID;
    }

    /**
     * Sets the value of the carID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCarID(BigInteger value) {
        this.carID = value;
    }

}
