//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 01:59:08 PM MSK 
//


package by.it.romankov.jd02_09;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReapetedClients complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReapetedClients">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReapetedClient" type="{http://jd02_09.romankov.it.by}ReapetedClient" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReapetedClients", propOrder = {
    "reapetedClient"
})
public class ReapetedClients {

    @XmlElement(name = "ReapetedClient", required = true)
    protected List<ReapetedClient> reapetedClient;

    /**
     * Gets the value of the reapetedClient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reapetedClient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReapetedClient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReapetedClient }
     * 
     * 
     */
    public List<ReapetedClient> getReapetedClient() {
        if (reapetedClient == null) {
            reapetedClient = new ArrayList<ReapetedClient>();
        }
        return this.reapetedClient;
    }

    @Override
    public String toString() {
        return "ReapetedClients{" +
                "reapetedClient=" + reapetedClient +
                '}';
    }
}
