//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.30 at 11:08:32 PM MSK 
//


package by.it.lyukovich.jd_02_09;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BookAuthor complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookAuthor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuthorID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AuthorName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AuthorCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookAuthor", propOrder = {
    "authorID",
    "authorName",
    "authorCountry"
})
public class BookAuthor {

    @XmlElement(name = "AuthorID")
    protected int authorID;
    @XmlElement(name = "AuthorName", required = true)
    protected String authorName;
    @XmlElement(name = "AuthorCountry", required = true)
    protected String authorCountry;

    /**
     * Gets the value of the authorID property.
     * 
     */
    public int getAuthorID() {
        return authorID;
    }

    /**
     * Sets the value of the authorID property.
     * 
     */
    public void setAuthorID(int value) {
        this.authorID = value;
    }

    /**
     * Gets the value of the authorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * Sets the value of the authorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorName(String value) {
        this.authorName = value;
    }

    /**
     * Gets the value of the authorCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorCountry() {
        return authorCountry;
    }

    /**
     * Sets the value of the authorCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorCountry(String value) {
        this.authorCountry = value;
    }

    @Override
    public String toString() {
        return "BookAuthor{" +
                "authorID=" + authorID +
                ", authorName='" + authorName + '\'' +
                ", authorCountry='" + authorCountry + '\'' +
                '}';
    }
}
