//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.30 at 11:08:32 PM MSK 
//


package by.it.lyukovich.jd_02_09;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BookAuthors complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookAuthors"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BookAuthor" type="{http://it-academy.by/lyukovich}BookAuthor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookAuthors", propOrder = {
    "bookAuthor"
})
public class BookAuthors {

    @XmlElement(name = "BookAuthor")
    protected List<BookAuthor> bookAuthor;

    @Override
    public String toString() {
        return "BookAuthors{" +
                "bookAuthor=" + bookAuthor +
                '}';
    }

    public void setBookAuthor(List<BookAuthor> bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    /**
     * Gets the value of the bookAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBookAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookAuthor }
     * 
     * 
     */
    public List<BookAuthor> getBookAuthor() {
        if (bookAuthor == null) {
            bookAuthor = new ArrayList<BookAuthor>();
        }
        return this.bookAuthor;
    }

}
