//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.30 at 11:08:32 PM MSK 
//


package by.it.lyukovich.jd_02_09;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Book complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Book"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BookSysInfo" type="{http://it-academy.by/lyukovich}BookSysInfo"/&gt;
 *         &lt;element name="BookLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookAuthors" type="{http://it-academy.by/lyukovich}BookAuthors"/&gt;
 *         &lt;element name="BookCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookFileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookImgName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BookBuyInfo" type="{http://it-academy.by/lyukovich}BookBuyInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Book", propOrder = {
    "bookSysInfo",
    "bookLanguage",
    "bookName",
    "bookAuthors",
    "bookCountry",
    "bookDescription",
    "bookFileName",
    "bookImgName",
    "bookFormat",
    "bookBuyInfo"
})
public class Book {

    @XmlElement(name = "BookSysInfo", required = true)
    protected BookSysInfo bookSysInfo;
    @XmlElement(name = "BookLanguage", required = true)
    protected String bookLanguage;
    @XmlElement(name = "BookName", required = true)
    protected String bookName;
    @XmlElement(name = "BookAuthors", required = true)
    protected BookAuthors bookAuthors;
    @XmlElement(name = "BookCountry", required = true)
    protected String bookCountry;
    @XmlElement(name = "BookDescription", required = true)
    protected String bookDescription;
    @XmlElement(name = "BookFileName", required = true)
    protected String bookFileName;
    @XmlElement(name = "BookImgName", required = true)
    protected String bookImgName;
    @XmlElement(name = "BookFormat", required = true)
    protected String bookFormat;
    @XmlElement(name = "BookBuyInfo", required = true)
    protected BookBuyInfo bookBuyInfo;

    /**
     * Gets the value of the bookSysInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BookSysInfo }
     *     
     */
    public BookSysInfo getBookSysInfo() {
        return bookSysInfo;
    }

    /**
     * Sets the value of the bookSysInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookSysInfo }
     *     
     */
    public void setBookSysInfo(BookSysInfo value) {
        this.bookSysInfo = value;
    }

    /**
     * Gets the value of the bookLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookLanguage() {
        return bookLanguage;
    }

    /**
     * Sets the value of the bookLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookLanguage(String value) {
        this.bookLanguage = value;
    }

    /**
     * Gets the value of the bookName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * Sets the value of the bookName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookName(String value) {
        this.bookName = value;
    }

    /**
     * Gets the value of the bookAuthors property.
     * 
     * @return
     *     possible object is
     *     {@link BookAuthors }
     *     
     */
    public BookAuthors getBookAuthors() {
        return bookAuthors;
    }

    /**
     * Sets the value of the bookAuthors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookAuthors }
     *     
     */
    public void setBookAuthors(BookAuthors value) {
        this.bookAuthors = value;
    }

    /**
     * Gets the value of the bookCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookCountry() {
        return bookCountry;
    }

    /**
     * Sets the value of the bookCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookCountry(String value) {
        this.bookCountry = value;
    }

    /**
     * Gets the value of the bookDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookDescription() {
        return bookDescription;
    }

    /**
     * Sets the value of the bookDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookDescription(String value) {
        this.bookDescription = value;
    }

    /**
     * Gets the value of the bookFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookFileName() {
        return bookFileName;
    }

    /**
     * Sets the value of the bookFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookFileName(String value) {
        this.bookFileName = value;
    }

    /**
     * Gets the value of the bookImgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookImgName() {
        return bookImgName;
    }

    /**
     * Sets the value of the bookImgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookImgName(String value) {
        this.bookImgName = value;
    }

    /**
     * Gets the value of the bookFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookFormat() {
        return bookFormat;
    }

    /**
     * Sets the value of the bookFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookFormat(String value) {
        this.bookFormat = value;
    }

    /**
     * Gets the value of the bookBuyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BookBuyInfo }
     *     
     */
    public BookBuyInfo getBookBuyInfo() {
        return bookBuyInfo;
    }

    /**
     * Sets the value of the bookBuyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookBuyInfo }
     *     
     */
    public void setBookBuyInfo(BookBuyInfo value) {
        this.bookBuyInfo = value;
    }

    @Override
    public String toString() {
        return "Book{" +
                "bookSysInfo=" + bookSysInfo +
                ", bookLanguage='" + bookLanguage + '\'' +
                ", bookName='" + bookName + '\'' +
                ", bookAuthors=" + bookAuthors +
                ", bookCountry='" + bookCountry + '\'' +
                ", bookDescription='" + bookDescription + '\'' +
                ", bookFileName='" + bookFileName + '\'' +
                ", bookImgName='" + bookImgName + '\'' +
                ", bookFormat='" + bookFormat + '\'' +
                ", bookBuyInfo=" + bookBuyInfo +
                '}';
    }
}
