//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.30 at 11:08:32 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it-academy.by/lyukovich", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.lyukovich.jd_02_09;
