//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.24 at 08:39:24 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it-academy.by/akhmelev", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.poprugo.jd02_09_mine;
