//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.24 at 08:39:24 AM MSK 
//


package by.it.poprugo.jd02_09_mine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Production complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Production"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Measure" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InProduction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="GetMaterials" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Fitting" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Refund" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Production", propOrder = {
    "measure",
    "inProduction",
    "getMaterials",
    "fitting",
    "refund"
})
public class Production {

    @XmlElement(name = "Measure", required = true)
    protected String measure;
    @XmlElement(name = "InProduction", required = true)
    protected String inProduction;
    @XmlElement(name = "GetMaterials", required = true)
    protected String getMaterials;
    @XmlElement(name = "Fitting", required = true)
    protected String fitting;
    @XmlElement(name = "Refund", required = true)
    protected String refund;

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasure(String value) {
        this.measure = value;
    }

    /**
     * Gets the value of the inProduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInProduction() {
        return inProduction;
    }

    /**
     * Sets the value of the inProduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInProduction(String value) {
        this.inProduction = value;
    }

    /**
     * Gets the value of the getMaterials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetMaterials() {
        return getMaterials;
    }

    /**
     * Sets the value of the getMaterials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetMaterials(String value) {
        this.getMaterials = value;
    }

    /**
     * Gets the value of the fitting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFitting() {
        return fitting;
    }

    /**
     * Sets the value of the fitting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFitting(String value) {
        this.fitting = value;
    }

    /**
     * Gets the value of the refund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefund() {
        return refund;
    }

    /**
     * Sets the value of the refund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefund(String value) {
        this.refund = value;
    }

}
